### ISSUE TITLE
How do you trigger a Sonarr import?

### ISSUE THREAD

**Issue by laryan61** [Davidtober/sonarr-import#1]
I have a script that does something similar, but not as elegant. Now with Sonarr v4, my API call to trigger an import is no longer working. Looking at your script, I don't see that it triggers a Sonarr import. Or does it?

**Comment by Davidtober** [comment]
Hi @laryan61 
Thanks for your interest in this repo. This script is intended to be run by Sonarr after an import operation is completed so it doesn't trigger the Sonarr import anywhere in the script.
